[book]
authors = ["the rustic authors"]
description = "rustic - fast, encrypted, and deduplicated backups"
language = "en"
multilingual = false
src = "src"
title = "rustic user documentation"

[output.html]
curly-quotes = true
default-theme = "ayu"
site-url = "/docs/"
git-repository-url = "https://github.com/rustic-rs/docs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/rustic-rs/docs/edit/main/{path}"
cname = "rustic.cli.rs"

[output.html.fold]
enable = true
level = 0
